# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master

pool:
  vmImage: 'windows-latest'

variables:
  buildConfiguration: 'Release'
  pathtosolution: 'EventPlanning'
  pathtoproject: 'EventPlanning/EventPlanning.Web'

steps:

- task: SonarCloudPrepare@1
  inputs:
    SonarCloud: 'p2connectionSonarCloud'
    organization: 'p2sonarcloud'
    scannerMode: 'MSBuild'
    projectKey: 'p2keysonarcloud'
    projectName: 'p2_azure_devops'

- script: dotnet build 
    --configuration $(buildConfiguration)
  workingDirectory: $(pathtosolution)
  displayName: 'dotnet build $(buildConfiguration)'

- task: SonarCloudAnalyze@1

- task: SonarCloudPublish@1
  inputs:
    pollingTimeoutSec: '300'

- task: AzureWebApp@1
  inputs:
    azureSubscription: 'Azure subscription 1(cdfdc896-8bae-429f-9986-39e7c94cad84)'
    appType: 'webAppLinux'
    appName: 'P2EventService'
    deployToSlotOrASE: true
    resourceGroupName: '200106-UTA-PRS-NET'
    slotName: 'production'
    package: '$(System.DefaultWorkingDirectory)/**/*.zip'